version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg16-dev
    restart: always
    environment:
      POSTGRES_DB: dotnet9
      POSTGRES_USER: stp
      POSTGRES_PASSWORD: stp@admin
      TZ: Asia/Bangkok
      POSTGRES_INITDB_ARGS: "-c listen_addresses='*'"
    ports:
      - "5432:5432"
    volumes:
      # Named volume—Docker will create an empty one on first run
      - pgdata:/var/lib/postgresql/data
      # Your custom configs “read-only” from host
      - /home/ubuntu/docker/pgconf:/pgconf:ro
    command:
      - postgres
      - "-c"
      - "config_file=/pgconf/postgresql.conf"
      - "-c"
      - "hba_file=/pgconf/pg_hba.conf"

volumes:
  pgdata:
